# Generated by Django 4.2.3 on 2023-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230726_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_facilities',
            fields=[
                ('campus_facilitiesID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('hours_of_operation', models.CharField(max_length=100)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$38EI2NpVX0WBeTJVEzCJbm$0JnpiklLfu4HDcN6cP7Zv6acxKISodDWeG0xRUuCLcY=', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('course_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField()),
                ('password', models.CharField(default='pbkdf2_sha256$600000$Xah5pg5aJ5T8vmoyGXJhvO$UYn7J4AsShEx82Ko14nUgWbR9QXQ5CR1VAmEE3MF7uw=', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='facilitiesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$oAghho4z99N2kqkoHg0at5$9Tc4PCMUFnxIAKQuPciGYv5VSk+5h9Z7nNk0COW/hs0=', max_length=128),
        ),
    ]
