# Generated by Django 4.2.3 on 2023-07-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$GTQcICFyIO1JoMXM0YxtgW$930JWquVr1WHD2Z1LNmM7q6JjLDhmsarj1l3Wlqpgok=', max_length=128),
        ),
    ]
