# Generated by Django 4.2.3 on 2023-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_facilities',
            fields=[
                ('campus_facilitiesID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('availabilty', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('hours_of_operation', models.CharField(max_length=100)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$ueNetZCvcYtBYCHWFSMz1w$16eZiOu44UZ58/fPRzGySJM1D2GmwFlWcuvWgBeiQa4=', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='facilitiesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$XCRN5UjS4lBp7SzK90o6ga$niczCP70kY8coTLZg9XjNT58ReXwzHfbjlu9xXvr11o=', max_length=128),
        ),
    ]
