# Generated by Django 4.2.3 on 2023-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instructor_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$BK89hLdQ0jpC3dsS4KKugP$fSDbSiNc/qRKFC0BR2V8IbP2ipZyQviMwrKWsl9Tkmo=', max_length=128),
        ),
    ]
