# Generated by Django 4.2.3 on 2023-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$O5xDoJJ5froItRHwpsqtLh$+AmK0+XmiTQIb+bvfaPpgWgvbqfM7uQF3oZpq1i9csQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VgAKCcKTpgXV00hOSzcrjQ$hMtWhIgThK/U2Vv0UuAEI0RFr/oflnWhRsNGYqVwIqI=', max_length=128),
        ),
    ]
