# Generated by Django 4.2.3 on 2023-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uLxPD9acvfGdLx0fGo5TVu$Vvz+coRIMCdHKOd+1TzGS0LpaYtsyGaN7ZmlVM5ExRw=', max_length=128),
        ),
    ]
