# Generated by Django 4.2.3 on 2023-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$gfzMqhxzpW20yip13TyiWg$jvHmw/5h2ORQvk1We0QO2Rlfy+ydYmNk5mIXQzppG+g=', max_length=128),
        ),
    ]
