# Generated by Django 4.2.3 on 2023-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_last_login_course_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$S3aygCOJSNJKSVH51dJwc3$A3gv6T1RBz6IJauUWAaB9atua0jSpMqzleXrh7VdR8M=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$li76mmK4bNBucTH3irDlLD$hhE0z0Gsbe9fPXjjvLdCcUt1YxN8RnoQYcNOkcZRdoE=', max_length=128),
        ),
    ]
