# Generated by Django 4.2.3 on 2023-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_campus_facilities_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus_facilities',
            name='availabilty',
        ),
        migrations.AddField(
            model_name='campus_facilities',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campus_facilities',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sJZOVaecJlsW09IxEPiynA$AkxsQYB4WoVqJbJCdoRbkDjky3JZyTUun51y8MhDlm0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Cz6Jb0x633bMH3bW1rHF5Z$PACHK+YepexzQxITqfDFKOFt4C+kM7pGwv5KRTtJAD8=', max_length=128),
        ),
    ]
