# Generated by Django 4.2.3 on 2023-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_campus_facilities_availabilty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_facilities',
            name='availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campus_facilities',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xENlXbWGLVAs48Sed796Iy$Zc9fxrX0MMojoE5uuICOJU1cH1EXasgUdCeagIoaQDw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$fPLDcizwgzFWkMC2UcULru$DYn/AbdguCmnmtxnGfu/v/rT030rziyRes3ZwbID8bM=', max_length=128),
        ),
    ]
