# Generated by Django 4.2.3 on 2023-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_course_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$N0EVeTgsKMM0tFIV2PE4OJ$YCvqmAIHAtmgGmxQjx+rB15ywEZ1NfTgCeoAy4i6l7Y=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$QAqamjzAoOI7Bt9VsAtdbO$GoX7n2ouel4hZEBN+4o2ZFKK7mOCxVGwS5Ir7xFmaec=', max_length=128),
        ),
    ]
