# Generated by Django 4.2.3 on 2023-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jrX63Ltj7tiu5gC6hR7D3Y$Lrm2b5LY3HmjDnritewq6mpSsgWhcogzX7f66pGeou4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KGtpZusfxLSjyzminwY5dC$XWQ9wycGrxTgaY83FWRajr1E+85Wun1BwWujg6aQZ4A=', max_length=128),
        ),
    ]
