# Generated by Django 4.2.3 on 2023-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_course_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wJ7bA7udfsucpAz7dtCzFg$5plqGtwRqzxaTY0moIDqxIyVJtFJKp2TcW6NJqvkp4Q=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$FSj3Gq5ocaZgIeC2O9T0Rt$AFuNPpeqRhurNIBL39SexxZMOsU4OvomRSt4Lsilwx8=', max_length=128),
        ),
    ]
